export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_ENQUIRY_TYPES_REQUEST = 'FETCH_ENQUIRY_TYPES_REQUEST';
export const FETCH_ENQUIRY_TYPES_SUCCESS = 'FETCH_ENQUIRY_TYPES_SUCCESS';
export const FETCH_ENQUIRY_TYPES_FAILURE = 'FETCH_ENQUIRY_TYPES_FAILURE';
